features/environment.py
features/test_util.py
node/datastore.py
node/db_store.py
node/dht.py
node/market.py
node/openbazaar_daemon.py
node/orders.py
node/transport.py
node/ws.py
tests/test_datastore.py
tests/test_db_store.py

This PR is dependent on #1110.

C0103 fixes 4, datastore and db_store changes

---

configure.sh

Since @Renelvon said `set -x` isn't really needed as @Renelvon said at #1156, I commented out `set -x` for all OSes, also fixed formatting a bit.
Clone of #1160

Commented `set -x` and added formatting improvements for configure.sh

---

html/css/dark.css
html/partials/settings.html

Moved some inline CSS into stylesheet and swapped out checkbox in fav our of bootstrap's button group in Settings pages.

Settings ui revisions

---

README.md

Added image with info on the amount of bitcoin that will be received for one pull request.

Added tip amount to README.md

---

html/controllers/market.js

Fixed duplicate peers appearing by changing the way they are added.
Peers are now checked on their public key.

Duplicate market fix

---

db/migrations/migration1.py
db/migrations/migration2.py
db/migrations/migration3.py
db/migrations/migration4.py
node/constants.py
node/db_store.py
node/setup_db.py

Passphrase must be supplied by the user in the runtime (#271) but until there is a login screen ready, it's  better if we move this sensitive value in the constants file. 
This PR introduces the DB_PASSPHRASE constant and modifies the db-relevant code accordingly.

Introduced DB_PASSPHRASE constant

---

html/css/app.css
html/partials/contracts.html
html/partials/dashboard.html

Responsive fixes for contract table and demo gifs

---

html/partials/modal/buyItem.html

Something that got missed with previous PR. For the love of God don't make me rebase this lol.

Allows you to view all images in a contract + responsive

---

node/openbazaar.py

Some cases where certain args don't work properly in dev mode

dev_mode command arg fixes

---

html/partials/user.html

Rebasing [Pull Request 1024](https://github.com/OpenBazaar/OpenBazaar/pull/1204)
looks like he's gone away, rebasing for him to get the ball moving.

Fix item link error (rebasing for MioQuispe)

---

node/connection.py

As per Brian's suggestion and Sam's test

Fix to periodic callback

---

html/controllers/contracts.js
html/controllers/market.js
html/partials/modal/addContract.html

Current UI for Adding Contracts is confusing for price. This should clear it up.
Fixes #1239

Add Euro value and UI Fix for new contracts

---

html/partials/modal/addContract.html

Image preview

---

html/controllers/contracts.js
node/market.py

In market.py I have taken item_keywords out of the contract and put it into the contract object. In contract.js I have taken from the contract object and put it into the js contract object.

make keywords appear on contract edit

---

configure.ps1

1) Update OpenSSL for Windows binary build to Win32OpenSSL-1_0_2a.exe
2) Change OpenSSL download protocol to https
3) Update GPG Win from 2.2.2 to 2.2.4 (self-signed cert, so I didn't change to https)
4) Update Python from 2.7.8 to 2.7.9

Update OpenSSL, GPGWin, Python

---

configure.ps1

related to https://github.com/OpenBazaar/OpenBazaar/issues/1252

re issue 1252, pysqlcipher gone for windows script.

---

.pylintrc
node/backuptool.py
node/ws.py
requirements.txt
test_requirements.txt

* Upgraded *most* dependencies to latest available editions. See commits for specific information about each package.
* Kept back `requests`, `tornado` and `Twisted` as the new APIs are possibly backwards-incompatible and need more thorough checking.
* Kept back `pyelliptic`. It upgrades from a SHA1 to SHA256 signatures, which, while being an excellent move, splits the network. We need to think about that more.
* Fixed a couple of `pylint` warnings.

Monthly dependency check and upgrade

---

configure.sh

Added sudo explanation to install script

---

node/openbazaar.py

Call correct get_nat_status()

---

html/index.html
html/partials/contracts.html
html/partials/modal/addContract.html
html/partials/modal/buyItem.html
html/partials/modal/viewInboxMessage.html
html/partials/modal/viewOrder.html
html/partials/orders.html
html/partials/search.html
html/partials/user.html

Fix 404 image messages in console.log

---

node/market.py

Fixes #1209 
Cleans up the exception from bad reference to market_id

Reference market_id properly

---

html/partials/modal/addNode.html

Add required to Store GUID modal

---

html/controllers/contracts.js
html/partials/contracts.html
html/partials/modal/addContract.html

Fixes https://www.bountysource.com/issues/15949155-long-price-in-my-contracts-view-forces-edit-remove-buttons-offscreen
Fixes #1303

Create satoshis filter to fix long prices in contracts table.

---

configure.sh

@rippler does this fix #1320 for you?

Add haveged to Raspbian packages

---

node/transport.py

On startup nodes couldn't create a signed pubkey GUID due to cryptor not being setup.
Fixes #1318

Refactor create guid/sin to own method

---

rudp/pendingpacket.py

I think this fixes #1231 
Please test @Renelvon @SamPatt @zariok @ruxton

Timeout check killing Tornado ioloop

---

changelog
docs/openbazaar.1
node/constants.py

Please inform me of any errors you spot.

Prepare for 0.5.0 release

---

README.md

Bump the version number in README.

---

openbazaar

Fixes #1339  
This was causing issues with almost all installs. Will need to revisit the Arch problem.

Reverting 38046ec42f8500797ed3961f0f21a137d88c25f3

---

README.md

Slack badge and links

---

node/market.py
node/protocol.py
tests/test_protocol.py

Starting work on the issue #1119 and found a single instance in protocol.py which looked like a good place to start.
I added tests for the methods in this class and then removed the unused parameter and fixed up the code.

Start work on #1119

---

README.md

Credit to @SamPatt for this solution.

Update README.md for uninstall issue
