configure.sh

Found a fix for #1035. I don't know what `set -x` does, however, commenting it in the Ubuntu install suppresses it from listing the contents of `doneMessage`.
Is `set -x` required? Should it be commented out for all platforms?
Repost of 1155

comment out "set -x"

---

node/connection.py
node/dht.py

Grab a RLock object on running any method of a DHT object. Supposed to fix #801.
The lock is an RLock, so nested locks don't cause deadlocks.
The lock object had to be made public, since in connection.py, inCryptoPeerConnection.cb()  there is a piece of code that works with dht.activePeers().

DHT Locking

---

Vagrantfile
ansible-provisioning/README.md
ansible-provisioning/openbazaar_linux.yml

Working on https://github.com/OpenBazaar/OpenBazaar/issues/986
Goal is to have automatic setup +deploy ansible scripts for all architectures we want to support. We can have one setup.yml which will do slightly different things depending on the architecture. Some questions that came up:
-Do we want to support CentOS? - It is possible to have python2.7 there as well via anaconda.
-What happens when I want to include an Apache 2.0 snippet of code in this project, which I've modified (in this case the miniconda-centos role) ? I will ofc do a PR on the original repo to contribute to them as well.
Ansible works with vagrant (and apparently [docker](http://www.ansible.com/docker) but haven't tried it)

Ansible setup scripts for Ubuntu and Debian

---

requirements.txt

This updates pyqlcipher to version 2.6.4. There are two reason to update it. First of all this version downloads the amalgamation using https. It is also needed in order to remove all windows specific hacks from the configuration scripts and fix build for windows.

Use pysqlcipher version 2.6.4

---

configure.sh

I started with fixing a typo, wound up changing the whole message. Already tested, but it's always nice to have another LGTM. Lemme know if you want a squash. :smile:
The ending configure message now outputs:
```
____                     ____                            
/ __ \                   |  _ \                           
| |  | |_ __   ___ _ __   | |_) | __ _ ______ _  __ _ _ __ 
| |  | |  _ \ / _ \  _ \  |  _ < / _` |_  / _` |/ _` |  __|
| |__| | |_) |  __/ | | | | |_) | (_| |/ / (_| | (_| | |   
\____/| .__/ \___|_| |_| |____/ \__,_/___\__,_|\__,_|_|   
| |                                                 
|_|                                                 
Beta 3.0
OpenBazaar configuration finished!
Run './openbazaar start; tail -F logs/production.log' to start OpenBazaar and …
```

Minor: changed `./configure` message

---

configure.sh
openbazaar

Our *nix configuration script is somewhat messy. Dependency versions have fallen out of date, especially on Fedora. Proper sandboxing via `virtualenv` is not enforced across installations. This PR is an attempt to fix some of the problems and factor repetitive code.  
* Factor creation of `virtualenv`.
* Use `virtualenv` on Gentoo.
* Do not parrot executed commands to output.
* Sanitize Fedora configuration: upgrade `bitcoin-release` to version `1.6`; prune unneeded dependencies
* FIX `LD_LIBRARY_PATH` before launching OpenBazaar on Fedora.
* Expanded flags to long-form, thanks to @chatcannon.
* Minor fixes and grooming.

Fix, update and refactor configuration script.

---

configure.sh

Rather than running ‘brew upgrade’ which will upgrade every package
installed on the system, only upgrade those that we need.

Only upgrade necessary dependencies in brew upgrade. Fixes #1178

---

node/openbazaar.py

When adding the `command` argument, set nargs to '?' (accept 0 or 1) and
make the default command `help` to print usage. This avoids printing an
error when no command is given.

Bugfix: Make command line arguments optional

---

scripts/banditcheck.sh
scripts/pycheck.sh

The `bandit` security checker was installed on the build on #1085. Because `bandit` isn't on pypi, we are downloading and installing the latest version. This occasionally causes the build to break, as `bandit` is under active development. This PR causes the build to ignore the exit status of the relevant checking script, which is in line with our policy to using `bandit` only for informative purposes.
* Force exit status of `scripts/banditcheck.sh` to be `0`.

Fix build: Ignore bandit exit status

---

openbazaar

Don't start the openbazaar process as a background job. This makes it
easier to keep track of the process when it is run in the terminal.

Run in foreground by default

---

node/dht.py

I had an error from this typo in my log:
```
ERROR - Exception in callback <bound method DHT._refresh_node of <node.dht.DHT object at 0x10b533f90>>
Traceback (most recent call last):
File "/Users/xtian/Projects/src/openbazaar/env/lib/python2.7/site-packages/tornado/ioloop.py", line 976, in _run
return self.callback()
File "node/dht.py", line 40, in synced_f
return f(self, *args, **kwargs)
File "node/dht.py", line 331, in _refresh_node
self._republish_data()
File "node/dht.py", line 40, in synced_f
return f(self, *args, **kwargs)
File "node/dht.py", line 354, in _republish_data
self._threadedRepublishData()
AttributeError: 'DHT' object has no attribute '_threadedRepublishData'
```

_threadedRepublishData -> _threaded_republish_data

---

node/connection.py
node/dht.py

Currently the OB software has high CPU usage and network consumption due to pinging dead peers when it should not.

CPU/Network Utilization Tweak

---

node/connection.py
node/market.py
node/openbazaar_daemon.py
node/transport.py
rudp/pendingpacket.py

IOLoop.instance() is only meant to be used when posting back to the
main thread, invoking this method performs double checks on a critical
code section, too many calls and you can end up on deadlocks.
It is better to use IOLoop.current(), which could in turn use .instance()
only if it were necessary.
I've debugged our code and we only have 3 threads running (according to my PyCharm debugger)
Therefore in most of the cases we're probably making those calls from the
same thread where Tornado's ioLoop thread lives.
I've also reduced the number of calls to IOLoop.current() by keeping a reference
to the loop in the constructor of the classes that need to communicate with it.
In all classes this reference is known as `self.loop`

Reduce expensive calls to ioloop.IOLoop.instance()

---

html/partials/modal/buyItem.html

now line breaks are working in the item description
(tested under windows with chrome 42)
Before the fix:
After the fix:

format item buy desc  (Purchase this Contract)

---

node/openbazaar_daemon.py

If for some reason an user decides to run the console process in
foreground (without the '&'), and then tries to stop the process
with `Ctrl-C`, we will have a proper shutdown occur.

MarketApplication.shutdown() called on SIGINT signal.

---

html/controllers/contracts.js

Minor bug fix in the 'Save Contract' function.  Ternary operator to check for existence of product keywords always returned true because empty array always exists.  The prevented the contract from saving.  Changed to check index 0 of array.

fixed check for keywords on contract save

---

configure.ps1

... so that it reflects the correct version of Gpg4win (2.2.4 instead of 2.2.2)

Update console notification message

---

html/controllers/contracts.js

Initialize $scope.contract.productKeywords as an empty array when opening modal to create a new contract.

fix for empty keywords on contract creation

---

README.md

This wasn't updated when the 4.0 changes were merged.

Correct release version in readme.md

---

node/constants.py
node/dht.py

This fix implements a new constant for close node info timeout. Right now if your node issues a key search against the DHT and it's not found by a peer they will return close nodes no matter if they're reachable or not. This imposes a 15 minute limit for when the peer was last seen. This should cut down on peers sending you stale lists of nodes to populate your sidebar.

Peers should only relay reachable close nodes

---

Dockerfile

This allows editing the code and Dockerfile without invalidating the docker cache with the installed requirements.

Add pip requirements separately

---

node/openbazaar.py

Fixes #1220 
Currently there is a -s --seeds parameter taken at the command line and it does nothing. This PR adds that functionality and adds a help description message for it.

Add seeds help

---

node/transport.py

Using a hash of the user's signed pubkey prevents an impersonation attack called Spartacus, which is the result of a node claiming to be another by passing it's GUID. By ensuring that GUIDs are signed pubkeys will allow the recipient node to validate that the node truly owns the GUID it claims as its own.

Generate GUID Use Signed Pubkey

---

.gitmodules
scripts/jscheck.sh
scripts/nlcheck.sh
scripts/pycheck.sh

* Remove unused `pybitmessage` git submodule.
* Remove references of `pybitmessage` in scripting files.
This PR does not remove any of the numerous (albeit non-functional) references to bitmessage inside `node`. This will be done carefully in a future PR, because there may be backwards-incompatible changes in some critical modules, e.g. the launcher.

Remove pybitmessage submodule

---

Dockerfile

Workaround for [issue 28 in python-gnupg 1.3.7](https://bitbucket.org/vinay.sajip/python-gnupg/issue/28)
Alternatively, the issue could be solved by setting os.environ['LOGNAME'] directly before the gpg call in node/transport.py.

Prevent a GPG key generation input exception on missing logname and username

---

node/transport.py

This value is always empty string and will generate a new GUID every time you start up the client.
@gubatron @Renelvon @drwasho @SamPatt 
This is a critical bug and should be pushed asap.

Critical Bug that Causes New GUID Everytime

---

node/market.py
test_requirements.txt
tests/test_market.py

Removed unused parameters for #1119. Found a bug where generate_new_pubkey would return the same pubkey for id's 1-9, then the same for 10-99, the same for 100-999 and so on.

Added tests for node/market.py.
